version: '2.3'
services:
  guestbook:
    build:
      context: ./
    entrypoint:
      - /bin/bash
    environment:
      count: 0
      result: ""
    command:
      - -e
      - -c
      - |
        /sampleapp/test_script.sh
    ports:
      - "8000:8000"

  mysql:
    image: "mysql:5"
    # volumes:
    #   - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
      MYSQL_USER: "guestbook"
      MYSQL_PASSWORD: "guestbook_pass"
      MYSQL_DATABASE: "test_guestbook"
    ports:
      # For maintenance access.
      - "3306:3306"
