apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deployment
  labels:
    app: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: "{{ .Values.image }}:{{ .Values.tag }}" 
        ports: 
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: guestbook-config
        env:
          - name: GUESTBOOK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: guestbook-secret
                key: GUESTBOOK_PASSWORD

        command: 
          - /bin/sh
          - -c
          - |
            python manage.py migrate --settings sampleapp.settings_prod
            python manage.py runserver 0.0.0.0:8000 --settings sampleapp.settings_prod
      initContainers:
      - name: mysql-waiter
        image: "mysql:5.7.14"
        envFrom:
          - configMapRef:
              name: guestbook-config
        env:
          - name: GUESTBOOK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: guestbook-secret
                key: GUESTBOOK_PASSWORD
        command:
          - /bin/bash
          - -c
          - |
            mysqladmin ping -u ${GUESTBOOK_USER} -p${GUESTBOOK_PASSWORD} --host ${GUESTBOOK_DATABASE_HOST} -w10